# Generated by Django 5.1.4 on 2026-07-21 09:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('source_type', models.CharField(choices=[('article', 'Article'), ('ticket', 'Ticket'), ('faq', 'FAQ')], default='article', max_length=20)),
                ('source_id', models.CharField(blank=True, default='', max_length=255)),
                ('tags', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
